name: Go CI

on:
  push:
    paths:
      - 'Go/**'
      - '.github/workflows/go-ci.yml'
  pull_request:
    paths:
      -'Go/**'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21.4'

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run Go Tests
      run: |
        cd Go
        for dir in $(find . -type f -name 'main_test.go' -exec dirname {} \; | sort -u); do
          echo "Running tests in $dir"
          (cd "$dir" && go test)
        done
  