name: Go Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16' # or the version you're using

    - name: Install golint
      run: go get -u golang.org/x/lint/golint

    - name: Run golint
      run: golint ./...
