name: Python CI

on:
  push:
    paths:
      - 'Python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    paths:
      - 'Python/**'

jobs:
  build:
    name: Test and Lint Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r Python/requirements.txt

    - name: Check code formatting with Black
      run: black --check ./Python

    - name: Run pytest
      run: pytest ./Python
