name: Python CI

on:
  push:
    paths:
      - 'Python/**'
  pull_request:
    paths:
      - 'Python/**'

jobs:
  build:
    name: Test and Lint Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # - name: Install dependencies
    #   run: pip install -r Python/requirements.txt
    #   working-directory: ./Python

    # - name: Lint with flake8
    #   run: flake8 ./Python
      # Only if you wish to include linting

    - name: Run pytest
      run: pytest ./Python
